# -*- coding: utf-8 -*-
"""프로그래밍 교수학습 프로젝트(15주차).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQ0DudFaSuRMUJptzL1kxMOP4LF0gwue
"""

import pandas as pd
import numpy as np

# 엑셀 파일 업로드로 데이터 불러오기
file_path = 'learning_data.xlsx'  # 엑셀 파일 경로
try:
    df = pd.read_excel(file_path)
except FileNotFoundError:
    print(f"파일을 찾을 수 없습니다. 파일 경로를 확인하세요: {file_path}")
    exit()

# 데이터 확인
print("업로드된 학습 데이터:")
print(df.head())  # 상위 5개 행 출력

# 사용자 입력: 학습자ID를 입력받아 검색
try:
    user_input = int(input("분석할 학습자의 ID를 입력하세요: ").strip())
except ValueError:
    print("유효한 숫자를 입력하세요!")
    exit()

# 현재 학습자의 데이터 검색
current_user_data = df[df['학습자ID'] == user_input]

if current_user_data.empty:
    print(f"학습자 ID {user_input}에 해당하는 데이터가 없습니다.")
else:
    # 각 주차별 평균 진도 속도 계산
    average_progress = df.iloc[:, 1:].mean()  # 모든 학습자의 평균 진도율
    current_user_progress = current_user_data.iloc[0, 1:]  # 현재 학습자의 진도율

    # 결과 비교 및 메시지 생성
    comparison = current_user_progress - average_progress  # 현재 학습자와 평균 비교

    print(f"\n학습자 ID {user_input} 진도 분석 결과:")
    for week, diff in comparison.items():
        if diff > 0:
            print(f"{week}: 평균보다 {diff:.2f}% 빠릅니다. 잘하고 있어요!")
        elif diff < 0:
            print(f"{week}: 평균보다 {abs(diff):.2f}% 느립니다. 조금만 더 힘내세요!")
        else:
            print(f"{week}: 평균 속도와 같습니다. 꾸준히 진행 중입니다!")

    # 최종 종합 결과 메시지
    overall_diff = current_user_progress.mean() - average_progress.mean()
    if overall_diff > 0:
        print("\n종합 평가: 전체적으로 평균보다 빠릅니다. 훌륭합니다!")
    elif overall_diff < 0:
        print("\n종합 평가: 전체적으로 평균보다 느립니다. 목표에 맞춰 노력해 보세요!")
    else:
        print("\n종합 평가: 전체적으로 평균과 동일합니다. 꾸준히 유지하세요!")